# -*- coding: utf-8 -*-
"""Silhouette Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xu0toRD2csoum5cpaVaYAFAGhNGG7BRg
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv("/content/IRIS.csv")

dataset.head(3)

sns.pairplot(data=dataset)



from sklearn.cluster import KMeans

wcss = []

for i in range(2,21):
  km = KMeans(n_clusters=i, init='k-means++')
  km.fit(dataset.drop('species', axis=1)) # Select only numerical columns
  wcss.append(km.inertia_)

plt.figure(figsize=(10, 5))
plt.plot([i for i in range(2, 21)], wcss,marker="o")
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.xticks([i for i in range(2,21)])
plt.ylabel('WCSS')
plt.grid()
plt.show()



from sklearn.metrics import silhouette_score



kmn = KMeans(n_clusters=3, random_state=42, n_init=10)
# Drop the 'predict' column if it exists before fitting
if 'predict' in dataset.columns:
    dataset = dataset.drop('predict', axis=1)
kmn.fit(dataset.drop('species', axis=1))
dataset["predict"] = kmn.labels_

display(kmn.labels_)



silhouette_score(dataset.drop('species', axis=1), kmn.labels_)





dataset



sns.pairplot(data=dataset,hue="predict")
plt.show()



org_dataset = pd.read_csv(r"/content/IRIS.csv")

sns.pairplot(data=org_dataset,hue="species")
plt.show()





ss = []
no_c = [j for j in range(2,21)]
for i in range(2,21):
  km1 = KMeans(n_clusters=i, n_init=10, random_state=42) # Added random_state and n_init for reproducibility
  km1.fit(dataset.drop('species', axis=1)) # Exclude the 'species' column
  ss.append(silhouette_score(dataset.drop('species', axis=1), km1.labels_)) # Exclude the 'species' column and corrected typo

plt.plot(no_c,ss)
plt.xlabel("no of cluster")
plt.ylabel("silhouette_score")
plt.xticks(no_c)
plt.grid(axis="x")
plt.show()

